services:
  mysql:
    image: mysql:8.0
    container_name: bookmyhotel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bookmyhotel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - bookmyhotel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Development tools
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: bookmyhotel-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bookmyhotel-network
    profiles:
      - dev

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: bookmyhotel-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - bookmyhotel-network
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: bookmyhotel-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - bookmyhotel-network
    profiles:
      - monitoring

volumes:
  mysql_data:
  prometheus_data:
  grafana_data:

networks:
  bookmyhotel-network:
    driver: bridge
