services:
  mysql:
    image: mysql:8.0
    container_name: bookmyhotel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bookmyhotel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - bookmyhotel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: bookmyhotel-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookmyhotel?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      APP_JWT_SECRET: your-very-long-secret-key-that-should-be-at-least-256-bits-long-for-security-in-production
      STRIPE_API_KEY: ${STRIPE_API_KEY:-sk_test_your_stripe_secret_key}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-whsec_your_webhook_secret}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bookmyhotel-network
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: bookmyhotel-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
      REACT_APP_STRIPE_PUBLISHABLE_KEY: ${REACT_APP_STRIPE_PUBLISHABLE_KEY:-pk_test_your_stripe_publishable_key}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - bookmyhotel-network

  # Development tools
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: bookmyhotel-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bookmyhotel-network
    profiles:
      - dev

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: bookmyhotel-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - bookmyhotel-network
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: bookmyhotel-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - bookmyhotel-network
    profiles:
      - monitoring

volumes:
  mysql_data:
  prometheus_data:
  grafana_data:

networks:
  bookmyhotel-network:
    driver: bridge
