CREATE TABLE IF NOT EXISTS uat_checklists (
    id BIGINT NOT NULL AUTO_INCREMENT,
    hotel_id BIGINT NOT NULL,
    tester_name VARCHAR(255) NULL,
    test_environment VARCHAR(255) NULL,
    test_date DATE NULL,
    build_version VARCHAR(100) NULL,
    hotel_tenant_tested VARCHAR(255) NULL,
    checklist_items_json LONGTEXT NULL,
    final_decision VARCHAR(64) NULL,
    qa_lead VARCHAR(255) NULL,
    business_owner VARCHAR(255) NULL,
    product_owner VARCHAR(255) NULL,
    approval_date DATE NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_uat_checklist_hotel UNIQUE (hotel_id),
    CONSTRAINT fk_uat_checklists_hotel FOREIGN KEY (hotel_id) REFERENCES hotels (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS uat_defects (
    id BIGINT NOT NULL AUTO_INCREMENT,
    hotel_id BIGINT NOT NULL,
    summary VARCHAR(255) NOT NULL,
    tester_detail LONGTEXT NULL,
    severity VARCHAR(32) NOT NULL,
    blocking_release BIT NOT NULL,
    admin_notes LONGTEXT NULL,
    fix_details LONGTEXT NULL,
    status VARCHAR(32) NOT NULL,
    created_by_user_id BIGINT NULL,
    updated_by_user_id BIGINT NULL,
    resolved_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_uat_defects_hotel FOREIGN KEY (hotel_id) REFERENCES hotels (id) ON DELETE CASCADE,
    CONSTRAINT fk_uat_defects_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_uat_defects_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    INDEX idx_uat_defects_hotel (hotel_id),
    INDEX idx_uat_defects_status (status),
    INDEX idx_uat_defects_severity (severity)
);